# 
# +------------------------------------------------------+ #
# |                       Notes                          | #
# +------------------------------------------------------+ #
ops-name-color: ''
nickname-prefix: ''
max-nick-length: 70
ignore-colors-in-max-nick-length: false
change-displayname: true
teleport-safety: true
force-disable-teleport-safety: false
teleport-cooldown: 0
teleport-delay: 0
teleport-invulnerability: 4
heal-cooldown: 30
near-radius: 200
permission-based-item-spawn: false
spawnmob-limit: 10
warn-on-smite: true
drop-items-if-full: false
notify-no-new-mail: true
socialspy-commands:
- msg
- w
- r
- mail
- m
- t
- whisper
- emsg
- tell
- er
- reply
- ereply
- email
- action
- describe
- eme
- eaction
- edescribe
- etell
- ewhisper
- pm
mute-commands:
- f
- kittycannon
player-commands:
- afk
- afk.auto
- back
- back.ondeath
- balance
- balance.others
- balancetop
- build
- chat.color
- chat.format
- chat.shout
- chat.question
- clearinventory
- compass
- depth
- delhome
- getpos
- geoip.show
- help
- helpop
- home
- home.others
- ignore
- info
- itemdb
- kit
- kits.tools
- list
- mail
- mail.send
- me
- motd
- msg
- msg.color
- nick
- near
- pay
- ping
- protect
- r
- rules
- realname
- seen
- sell
- sethome
- setxmpp
- signs.create.protection
- signs.create.trade
- signs.break.protection
- signs.break.trade
- signs.use.balance
- signs.use.buy
- signs.use.disposal
- signs.use.enchant
- signs.use.free
- signs.use.gamemode
- signs.use.heal
- signs.use.info
- signs.use.kit
- signs.use.mail
- signs.use.protection
- signs.use.repair
- signs.use.sell
- signs.use.time
- signs.use.trade
- signs.use.warp
- signs.use.weather
- spawn
- suicide
- time
- tpa
- tpaccept
- tpahere
- tpdeny
- warp
- warp.list
- world
- worth
- xmpp
skip-used-one-time-kits-from-kit-list: false
kits:
  Starter:
    delay: 86400
    items:
    - 267:0 1
    - 257:0 1
    - 258:0 1
    - 256:0 1
    - 306:0 1
    - 307:0 1
    - 308:0 1
    - 309:0 1
    - 364:0 64
  Valiant:
    delay: 86400
    items:
    - "276:0 1 damage_all:1 durability:1 name:\xa76\xa7k!\xa7eValiant\xa76\xa7k!"
    - "278:0 1 dig_speed:1 durability:1 name:\xa76\xa7k!\xa7eValiant\xa76\xa7k!"
    - "279:0 1 dig_speed:1 durability:1 name:\xa76\xa7k!\xa7eValiant\xa76\xa7k!"
    - "277:0 1 dig_speed:1 durability:1 name:\xa76\xa7k!\xa7eValiant\xa76\xa7k!"
    - "310:0 1 protection_environmental:1 durability:1 name:\xa76\xa7k!\xa7eValiant\xa7\
      6\xa7k!"
    - "311:0 1 protection_environmental:1 durability:1 name:\xa76\xa7k!\xa7eValiant\xa7\
      6\xa7k!"
    - "312:0 1 protection_environmental:1 durability:1 name:\xa76\xa7k!\xa7eValiant\xa7\
      6\xa7k!"
    - "313:0 1 protection_environmental:1 durability:1 name:\xa76\xa7k!\xa7eValiant\xa7\
      6\xa7k!"
    - "364:0 64 name:\xa76\xa7k!\xa7eValiant\xa76\xa7k!"
  Mystic:
    delay: 86400
    items:
    - "276:0 1 damage_all:3 durability:2 name:\xa75\xa7k!\xa7dMystic\xa75\xa7k!"
    - "278:0 1 dig_speed:3 durability:2 name:\xa75\xa7k!\xa7dMystic\xa75\xa7k!"
    - "279:0 1 dig_speed:3 durability:2 name:\xa75\xa7k!\xa7dMystic\xa75\xa7k!"
    - "277:0 1 dig_speed:3 durability:2 name:\xa75\xa7k!\xa7dMystic\xa75\xa7k!"
    - "310:0 1 protection_environmental:2 durability:2 name:\xa75\xa7k!\xa7dMystic\xa7\
      5\xa7k!"
    - "311:0 1 protection_environmental:3 durability:2 name:\xa75\xa7k!\xa7dMystic\xa7\
      5\xa7k!"
    - "312:0 1 protection_environmental:3 durability:2 name:\xa75\xa7k!\xa7dMystic\xa7\
      5\xa7k!"
    - "313:0 1 protection_environmental:2 durability:2 name:\xa75\xa7k!\xa7dMystic\xa7\
      5\xa7k!"
    - "364:0 64 name:\xa75\xa7k!\xa7dMystic\xa75\xa7k!"
  Arken:
    delay: 86400
    items:
    - "276:0 1 damage_all:5 durability:3 name:\xa73\xa7k!\xa7bArken\xa73\xa7k!"
    - "278:0 1 dig_speed:5 durability:3 name:\xa73\xa7k!\xa7bArken\xa73\xa7k!"
    - "279:0 1 dig_speed:5 durability:3 name:\xa73\xa7k!\xa7bArken\xa73\xa7k!"
    - "277:0 1 dig_speed:5 durability:3 name:\xa73\xa7k!\xa7bArken\xa73\xa7k!"
    - "310:0 1 protection_environmental:4 durability:3 name:\xa73\xa7k!\xa7bArken\xa7\
      3\xa7k!"
    - "311:0 1 protection_environmental:4 durability:3 name:\xa73\xa7k!\xa7bArken\xa7\
      3\xa7k!"
    - "312:0 1 protection_environmental:4 durability:3 name:\xa73\xa7k!\xa7bArken\xa7\
      3\xa7k!"
    - "313:0 1 protection_environmental:4 durability:3 name:\xa73\xa7k!\xa7bArken\xa7\
      3\xa7k!"
    - "364:0 64 name:\xa73\xa7k!\xa7bArken\xa73\xa7k!"
  ValiantBlocks:
    delay: 86400
    items:
    - 42:0 16
    - 152:0 16
    - 41:0 8
    - 133:0 8
    - 57:0 4
  MysticBlocks:
    delay: 86400
    items:
    - 42:0 32
    - 152:0 32
    - 41:0 16
    - 133:0 16
    - 57:0 8
  ArkenBlocks:
    delay: 86400
    items:
    - 42:0 64
    - 152:0 64
    - 41:0 32
    - 133:0 32
    - 57:0 16
sign-use-per-second: 4
backup:
  interval: 30
per-warp-permission: false
list:
  Admins: owner admin
debug: false
remove-god-on-disconnect: false
auto-afk: 300
auto-afk-kick: -1
freeze-afk-players: false
disable-item-pickup-while-afk: false
cancel-afk-on-interact: true
cancel-afk-on-move: true
afk-list-name: none
death-messages: true
allow-silent-join-quit: false
custom-join-message: none
custom-quit-message: none
world-teleport-permissions: false
default-stack-size: -1
oversized-stacksize: 64
repair-enchanted: true
unsafe-enchantments: false
register-back-in-listener: false
login-attack-delay: 5
max-fly-speed: 0.8
max-walk-speed: 0.8
mails-per-minute: 1000
max-tempban-time: -1
last-message-reply-recipient: true
last-message-reply-recipient-timeout: 180
milk-bucket-easter-egg: true
send-fly-enable-on-join: true
world-time-permissions: false
update-bed-at-daytime: true
world-home-permissions: false
sethome-multiple:
  default: 3
  vip: 5
  staff: 10
tpa-accept-cancellation: 120
starting-balance: 0
currency-symbol: $
max-money: 10000000000000
min-money: -10000
economy-log-enabled: false
use-bukkit-permissions: false
minimum-pay-amount: 0.001
non-ess-in-help: true
hide-permissionless-help: true
chat:
  radius: 0
  format: '{DISPLAYNAME}: {MESSAGE}'
protect:
  prevent:
    lava-flow: false
    water-flow: false
    water-bucket-flow: false
    fire-spread: true
    lava-fire-spread: true
    flint-fire: false
    lightning-fire-spread: true
    portal-creation: false
    tnt-explosion: false
    tnt-playerdamage: false
    tnt-minecart-explosion: false
    tnt-minecart-playerdamage: false
    fireball-explosion: false
    fireball-fire: false
    fireball-playerdamage: false
    witherskull-explosion: false
    witherskull-playerdamage: false
    wither-spawnexplosion: false
    wither-blockreplace: false
    creeper-explosion: false
    creeper-playerdamage: false
    creeper-blockdamage: false
    enderdragon-blockdamage: true
    enderman-pickup: false
    villager-death: false
    entitytarget: false
    spawn:
      creeper: false
      skeleton: false
      spider: false
      giant: false
      zombie: false
      slime: false
      ghast: false
      pig_zombie: false
      enderman: false
      cave_spider: false
      silverfish: false
      blaze: false
      magma_cube: false
      ender_dragon: false
      pig: false
      sheep: false
      cow: false
      chicken: false
      squid: false
      wolf: false
      mushroom_cow: false
      snowman: false
      ocelot: false
      iron_golem: false
      villager: false
      wither: false
      bat: false
      witch: false
      horse: false
  creeper:
    max-height: -1
  disable:
    fall: false
    pvp: false
    drown: false
    suffocate: false
    lavadmg: false
    projectiles: false
    contactdmg: false
    firedmg: false
    lightning: false
    wither: false
    weather:
      storm: false
      thunder: false
      lightning: false
    build: true
    use: true
    warn-on-build-disallow: true
  alert:
    on-placement: 10,11,46,327
    on-use: 327
  blacklist:
    placement: 10,11,46,327
    usage: 327
newbies:
  announce-format: '&dWelcome {DISPLAYNAME}&d to the server!'
  spawnpoint: newbies
  kit: tools
respawn-listener-priority: high
respawn-at-home: false
