#
#  ________  ________  ________  ________  _______   ________  ________  ________  ________  ________
# |\   ____\|\   ____\|\   __  \|\   __  \|\  ___ \ |\   __  \|\   __  \|\   __  \|\   __  \|\   ___ \
# \ \  \___|\ \  \___|\ \  \|\  \ \  \|\  \ \   __/|\ \  \|\ /\ \  \|\  \ \  \|\  \ \  \|\  \ \  \_|\ \
#  \ \_____  \ \  \    \ \  \\\  \ \   _  _\ \  \_|/_\ \   __  \ \  \\\  \ \   __  \ \   _  _\ \  \ \\ \
#   \|____|\  \ \  \____\ \  \\\  \ \  \\  \\ \  \_|\ \ \  \|\  \ \  \\\  \ \  \ \  \ \  \\  \\ \  \_\\ \
#    ____\_\  \ \_______\ \_______\ \__\\ _\\ \_______\ \_______\ \_______\ \__\ \__\ \__\\ _\\ \_______\
#    |\_________\|_______|\|_______|\|__|\|__|\|_______|\|_______|\|_______|\|__|\|__|\|__|\|__|\|_______|
#   \|_________|


settings:
  # By enabling lagg prevention Scoreboard will run asynchroniously
  # This means that it does not obstruct the main thread and thus causes a *LOT* let lagg.
  lag-prevention: true

hooks:
   # To what plugins should we hook into?
   placeholderapi: true
   mvdwplaceholderapi: true