# Configuration explanation below ~ 
# 
# ALL TIMES ARE IN SECONDS!
# Initial delay is the time before the plugin starts starting 
# the commands in the schedule. This is in place so that other
# plugins have the time to start. You could set this to 0, 
# but errors may occur.
# Make sure the Command1, Command2, Command3 etc. are numbered
# in succession. This will ensure they all load.
# 
# Also make sure you enter a command, heh.
# 
# 1 minute = 60 seconds. 1 hour = 3600 seconds
# HOUR in 24-hour format!
# SpecificTime commands ALWAYS repeat!

CheckUpdates: true
InitialDelay: 5
CommandSchedule:
  Command1:
    After: 5
    Repeat: true
    Interval: 600
    Command: broadcast &b&lConsider &3&lDonating &b&lto recieve awesome ranks & rewards! &3&lhttp://bit.ly/ArkenShop
  Command2:
    After: 5
    Repeat: true
    Interval: 660
    Command: broadcast &b&lCheck out our &3&lForums &b&lto interact with the community! &3&lhttp://bit.ly/ArkenForums
  Command3:
    After: 5
    Repeat: true
    Interval: 720
    Command: broadcast &b&lDon't forget to join our &3&lDiscord &b&lserver for a free Arcane Key! &3&lhttp://bit.ly/ArkenDiscord
