#   _____ _    _  _____ _______ ____  __  __      _  ____ _____ _   _ 
#  / ____| |  | |/ ____|__   __/ __ \|  \/  |    | |/ __ \_   _| \ | |
# | |    | |  | | (___    | | | |  | | \  / |    | | |  | || | |  \| |
# | |    | |  | |\___ \   | | | |  | | |\/| |_   | | |  | || | | . ` |
# | |____| |__| |____) |  | | | |__| | |  | | |__| | |__| || |_| |\  |
#  \_____|\____/|_____/   |_|  \____/|_|  |_|\____/ \____/_____|_| \_|
First-Join-Message: '&8[&a+&8]&b Welcome &3{playername}! &bYou are the {playercounter}th
  player to join the server!'
Join-Message: '&8[&a+&8]&3 {playername} &bjoined the server!'
Join-Commands: /spawn
Set-Inventory: false
Quit-Message: '&8[&c-&8]&3 {playername} &bleft the server!'
Player-Counter: 171
Sound:
  Activate-On-Join: false
  Require-Premission: false
  Type: EXPLODE
  Repeat: 0
  Tick-Delay: 5
Spawn:
  Activate-On-Join: true
  World: Lobby2
Firework:
  Activate-On-Join: true
  Type: BALL_LARGE
  Color:
    R: 0
    G: 255
    B: 255
  ColorFade:
    R: 255
    G: 0
    B: 0
